sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - ./gradlew war

script:
  - docker build -t bonte/kickoffkata .
  - docker run --rm=true -d -p 8081:8080 bonte/kickoffkata
  - curl -s http://localhost:8081/kick-off-kata-1.0-SNAPSHOT/hello | grep -a "Hello World!"